- hosts: centos
  become: yes
  tasks:
    - name: Copy rpm
      copy:
        src: cache-api-1.0-1.el10.noarch.rpm
        dest: /tmp/cache-api.rpm

    - name: Install rpm
      dnf:
        name: /tmp/cache-api.rpm
        state: present
        disable_gpg_check: yes

    - name: Start service
      systemd:
        name: cache-api
        enabled: yes
        state: started
